### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: TC9cfvSb791a74464e03ce53L9SDcSl2

origin=64999&destination=64942&weight=1000&courier=jne